CREATE TABLE game (
  id INTEGER PRIMARY KEY NOT NULL,
  created BIGINT NOT NULL
);

CREATE TABLE moves (
  id INTEGER PRIMARY KEY NOT NULL,
  created BIGINT NOT NULL,
  game_id INTEGER NOT NULL,
  player_move TEXT NOT NULL
);
